version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - CONFIGURATION: Debug
  - CONFIGURATION: Release

before_build:
    - cmake -D UNIT_TEST=ON -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\ark_cpp_client.sln

test_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%\test\%CONFIGURATION%\ark_cpp_client_tests.exe'
