version: 2
jobs:
  build-linux:
    machine: true
    steps:
      - checkout
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./travis/*.sh
      - run:
          name: Install
          command: ./travis/install_platform_io.sh
      - run:
          name: Build
          command: ./travis/script_platform_io.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux