version: 2
jobs:
  build-linux-default:
    machine: true
    steps:
      - checkout
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./travis/*.sh
      - run:
          name: Install
          command: ./travis/install_platform_io.sh
      - run:
          name: Build
          command: ./travis/script_platform_io.sh
  build-linux-gcc7:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository ppa:ubuntu-toolchain-r/test 
            sudo apt-add-repository ppa:george-edison55/cmake-3.x
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install g++-7 lcov
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./travis/*.sh
      - run:
          name: Environment variables
          command: CC=gcc-7 && CXX=g++-7
      - run:
          name: Build
          command: ./travis/script_desktop.sh
  build-linux-clang-5:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
            sudo apt-add-repository ppa:george-edison55/cmake-3.x
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install clang-5.0 lcov
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./travis/*.sh
      - run:
          name: Environment variables
          command: CC=clang-5.0 && CXX=clang++-5.0
      - run:
          name: Build
          command: ./travis/script_desktop.sh

          

workflows:
  version: 2
  build:
    jobs:
      - build-linux-default
      - build-linux-gcc7
      - build-linux-clang-5